const insolvency = [
    {
        "Case No.": "C.R.P.(PD) No.1289 of 2021",
        "Case Name": "Rohit Nath @ Rohit Rabindra Nath vs KEB Hana Bank Ltd",
        "Date": "28-07-2021",
        "Court": "High Court of Judicature at Madras",
        "Case Status": "Disposed off",
        "Judges Involved": "Sanjib Banerjee, Senthilkumar Ramamoorthy",
        "Sections and Clauses": "Section 95(1), Section 79(1), Section 60, Section 3(8), Section 3(7), Section 94(1), Section 243, Section 238, Section 2(c), Section 179(1), Section 60(2), Section 128, Section 2",
        "Facts": "The petitioner (guarantor) was a guarantor for a loan provided to a corporate entity by the respondent bank. The petitioner failed to pay the loan. The respondent bank served a notice demanding payment. The petitioner responded with a settlement suggestion, but the bank rejected it. The bank initiated insolvency proceedings against the petitioner before the Debts Recovery Tribunal.",
        "Petition Filed": "The petitioner filed a civil revision petition to strike off the insolvency proceedings initiated by the bank.",
        "Legal Issues": "The legal issues raised were whether an individual guarantor for a corporate debtor could be subject to insolvency proceedings under the Insolvency and Bankruptcy Code, 2016 (IBC) and whether the Debts Recovery Tribunal was the appropriate forum for such proceedings.",
        "Key Legal Questions": "Whether an individual guarantor for a corporate debtor can be subjected to insolvency proceedings under the Insolvency and Bankruptcy Code, 2016 (IBC) before the Debts Recovery Tribunal.",
        "Plaintiff's Arguments": "The petitioner argued that the IBC provisions relating to insolvency resolution processes for personal guarantors to corporate debtors were not yet fully implemented and that the relevant sections of the IBC should be interpreted narrowly. The petitioner also claimed that the bank had not exhausted its remedies against the corporate debtor before proceeding against the guarantor.",
        "Defendant's Arguments": "The respondent bank argued that the IBC clearly provides for the initiation of insolvency proceedings against individual guarantors of corporate debtors before the Debts Recovery Tribunal. The bank also asserted that it was not obligated to exhaust its remedies against the corporate debtor before proceeding against the guarantor.",
        "Court's Reasoning": "The court found that the IBC, specifically Section 95(1), read with Section 79(1) and other relevant sections, clearly allows a creditor to initiate insolvency proceedings against a guarantor before the Debts Recovery Tribunal. The court rejected the petitioner's arguments, finding that the relevant provisions of the IBC were fully implemented and that the petitioner's interpretation was narrow and impermissible. The court also held that the liability of a guarantor is co-extensive with that of the principal debtor, and the bank was not required to exhaust its remedies against the corporate debtor before proceeding against the guarantor.",
        "Decision": "The court dismissed the petitioner's civil revision petition and ordered the petitioner to pay costs of Rs. 50,000 to the respondent bank.",
        "Conclusion": "The court held that the Insolvency and Bankruptcy Code, 2016 allows creditors to initiate insolvency proceedings against individual guarantors of corporate debtors before the Debts Recovery Tribunal, even if the corporate debtor is not subject to insolvency proceedings.",
        "Case Summary": "The petitioner, a guarantor for a loan provided to a corporate entity, sought to strike off insolvency proceedings initiated by the bank. The petitioner argued that the relevant IBC provisions were not fully implemented and that the bank should have exhausted its remedies against the corporate debtor first. However, the court found that the IBC provisions were fully implemented and that the petitioner's interpretation was impermissible. The court held that the Debts Recovery Tribunal was the appropriate forum for such proceedings and that the bank was not required to exhaust its remedies against the corporate debtor before proceeding against the guarantor. The court dismissed the petition and ordered the petitioner to pay costs.",
        "": ""
    },
    {
        "Case No.": "Crl.O.P.No.24025 of 2017 and Crl.M.P.Nos.13909 of 2017 and 8366 of 2018",
        "Case Name": "M/s.Nag Leathers Pvt Ltd vs M/s.Saroj Leathers",
        "Date": "04-02-2019",
        "Court": "High Court of Judicature at Madras",
        "Case Status": "Disposed off",
        "Judges Involved": "G.K.Ilanthiraiyan",
        "Sections and Clauses": "Section 138 r/w 141 and 142 of Negotiable Instruments Act, Section 9 and Section 14 of the Insolvency and Bankruptcy Code, 2016",
        "Facts": "Nag Leathers Pvt Ltd issued a cheque to Saroj Leathers for Rs.73,51,408/- for the supply of wet blue stock. The cheque bounced and Saroj Leathers initiated proceedings under Section 138 of the Negotiable Instruments Act. Meanwhile, Nag Leathers Pvt Ltd was declared insolvent, and an Interim Resolution Professional was appointed.",
        "Petition Filed": "The petitioner, Nag Leathers Pvt Ltd, filed a petition under Section 482 Cr.P.C. seeking to quash the proceedings in S.T.C.No.76 of 2017 on the file of the learned District Munsif cum Judicial Magistrate, Ranipet, Vellore District, arguing that the initiation of proceedings under Section 138 of the Negotiable Instruments Act is barred due to the insolvency proceedings.",
        "Legal Issues": "Whether the initiation of proceedings under Section 138 of the Negotiable Instruments Act against a company that is under insolvency proceedings is barred?",
        "Key Legal Questions": "The petitioner argued that the proceedings under Section 138 of the Negotiable Instruments Act are barred under Section 14 of the Insolvency and Bankruptcy Code, 2016.",
        "Plaintiff's Arguments": "The respondent argued that the initiation of proceedings under Section 138 of the Negotiable Instruments Act is a statutory one and is distinct from the proceedings under the Insolvency and Bankruptcy Code, 2016. They argued that Section 14 of the Insolvency and Bankruptcy Code, 2016 prohibits the institution of suits or continuation of pending suits or proceedings against the Corporate Debtor, but does not prohibit criminal proceedings.",
        "Defendant's Arguments": "The court held that the offence under the Negotiable Instruments Act is a statutory one and the proceedings under the Negotiable Instruments Act are completely different from the Corporate Insolvency Resolution process under the Insolvency and Bankruptcy Code, 2016. The court further held that Section 14 of the Insolvency and Bankruptcy Code, 2016 prohibits the institution of suits or continuation of pending suits or proceedings against the Corporate Debtor, but does not prohibit criminal proceedings.",
        "Court's Reasoning": "The court dismissed the petition, finding no merit in the petitioner's arguments.",
        "Decision": "The Criminal Original Petition was dismissed.",
        "Conclusion": "The court found that the proceedings under Section 138 of the Negotiable Instruments Act are not barred by the insolvency proceedings, as the bar under Section 14 of the Insolvency and Bankruptcy Code, 2016 applies to civil proceedings, not criminal proceedings.",
        "Case Summary": "The petitioner argued that the insolvency proceedings barred the continuation of criminal proceedings against them under Section 138 of the Negotiable Instruments Act. The respondent argued that the proceedings under the Negotiable Instruments Act are separate from insolvency proceedings and not prohibited under the code. The court agreed with the respondent, finding that Section 14 of the Insolvency and Bankruptcy Code, 2016 only prohibits civil proceedings against a corporate debtor and not criminal proceedings. The court dismissed the petition, finding no merit in the petitioner's arguments.",
        "": ""
    },
    {
        "Case No.": "W.P.No.3659 of 2021",
        "Case Name": "M/s.Appollo Distilleries vs Union Of India",
        "Date": "08-04-2021",
        "Court": "HIGH COURT OF JUDICATURE AT MADRAS",
        "Case Status": "Disposed off",
        "Judges Involved": "Sanjib Banerjee, P.D.Audikesavalu",
        "Sections and Clauses": "Article 226 of the Constitution of India",
        "Facts": "The matter involves corporate insolvency proceedings of Empee Distilleries Limited. A resolution plan was accepted by the NCLT, but the petitioner argued that a share transaction between the 4th and 16th respondents should be deemed to have gone through since it wasn't avoided by an order prior to the resolution plan being accepted. The successful resolution applicant argued that the transaction involved valuable assets and should be reversed.",
        "Petition Filed": "Petition filed under Article 226 of the Constitution of India for issuance of a Writ of Certiorarified Mandamus calling for the records pertaining to the proceedings in MA/731/IB/2019 in CP/280/(IB)/2018 dated 27/06/2019 on the file of the 2nd respondent and quash the same as bereft of jurisdiction.",
        "Legal Issues": "The legal issue is whether the NCLT has jurisdiction to continue with the avoidance application after the resolution plan has been accepted.",
        "Key Legal Questions": "Does the NCLT have jurisdiction to continue with the avoidance application after the resolution plan has been accepted?",
        "Plaintiff's Arguments": "The petitioner argued that the transaction is deemed to have gone through since it wasn't avoided by an order prior to the resolution plan being accepted.",
        "Defendant's Arguments": "The successful resolution applicant argued that the transaction involved valuable assets and should be reversed.",
        "Court's Reasoning": "The court found that the legal issue raised was substantial, but ultimately decided to let the NCLT decide the matter. The court stated that the NCLT should dispose of the avoidance application as expeditiously as possible, and there should be no further transactions in the shares of the petitioner.",
        "Decision": "The court disposed of the petition by requesting the NCLT to dispose of the avoidance application as expeditiously as possible. The court also directed that there should be no further transactions in the shares of the petitioner until the NCLT makes a decision.",
        "Conclusion": "The court determined that the NCLT should determine the legal issue of whether it has jurisdiction to continue with the avoidance application after the resolution plan has been accepted.",
        "Case Summary": "The petitioner argued that the NCLT had no jurisdiction to continue with the avoidance application after the resolution plan was accepted. The successful resolution applicant argued that the transaction should be reversed. The court decided to defer to the NCLT's expertise and let it decide the legal issue. The court also imposed a temporary hold on further transactions in the shares of the petitioner.",
        "": ""
    },
    {
        "Case No.": "C.M.A(MD)Nos.656 and 657 of 2018 and C.R.P.(MD)No.1940 of 2018",
        "Case Name": "L.Arockiadoss vs J.Kannaperuman",
        "Date": "14-06-2024",
        "Court": "Madurai Bench of Madras High Court",
        "Case Status": "Disposed off",
        "Judges Involved": "The Honourable Mr.Justice K.Murali Shankar",
        "Sections and Clauses": "Order 41 Rule C.P.C., XXI Rule 97 C.P.C., Section 115 of Civil Procedure Code, Section 4 and 53 of the Provincial Insolvency Act, 1920, Section 9 of the Provincial Insolvency Act, 1920, Section 53 of the Provincial Insolvency Act, 1920, Section 37 of the Provincial Insolvency Act, 1920",
        "Facts": "The case involved a property dispute between a decree holder (Kamaraj) and a court auction purchaser (Arockiadoss) arising from an insolvency petition filed by the judgment debtor (Viswanath). The decree holder sought to execute a decree for Rs.5,75,000/- against the judgment debtor who had previously filed an insolvency petition. The insolvency court had annulled sale deeds executed by the judgment debtor. Arockiadoss, the court auction purchaser, sought delivery of the property, which was challenged by J.Kannaperuman and Sigappai, who claimed to have purchased the property from Viswanath.",
        "Petition Filed": "The petition was filed by the Court auction purchaser (Arockiadoss) seeking delivery of the property.",
        "Legal Issues": "The legal issues involved the jurisdiction of the Insolvency Court to annul sales, the validity of the annulment order, the effect of the annulment order after dismissal of the Insolvency Petition, the doctrine of lis pendens, and the alleged suppression and fraud in the auction sale proceedings.",
        "Key Legal Questions": "The key legal question was whether the order of the Insolvency Court annulling the sale deeds was valid and binding, given that the petition was filed before the judgment debtor was adjudged insolvent and the insolvency petition was later dismissed for default.",
        "Plaintiff's Arguments": "The plaintiff argued that the Insolvency Court had jurisdiction to annul the sale deeds, that the order was legally valid, and that the annulment order remained effective even after the dismissal of the insolvency petition. The plaintiff further argued that the auction sale proceedings were vitiated by suppression and fraud by the decree holder and the court auction purchaser, and that the value of the property was deliberately underestimated.",
        "Defendant's Arguments": "The defendant argued that the Insolvency Court had no jurisdiction to annul the sale deeds as the judgment debtor was not adjudged insolvent at the time of the petition. The defendant argued that the annulment order became ineffective upon the dismissal of the insolvency petition and that the claimants were not bonafide purchasers. The defendant also argued that the claimants did not plead fraud and did not provide evidence to support their claims.",
        "Court's Reasoning": "The court held that the Insolvency Court had no jurisdiction to annul the sale deeds as the judgment debtor was not adjudged insolvent. The court concluded that the annulment order was without jurisdiction and void. The court further held that the annulment order became ineffective after the dismissal of the insolvency petition. The court found that the decree holder and the court auction purchaser had suppressed material facts and committed fraud on the court and the claimants.",
        "Decision": "The court dismissed the appeals and the revision petition. The court directed the decree holder to deposit the amount withdrawn from the court deposit and ordered the court auction purchaser to withdraw the amount upon such deposit.",
        "Conclusion": "The court found that the Insolvency Court's order annulling the sale deeds was void and ineffective, as the judgment debtor was not adjudged insolvent at the time of the petition. The court also found that the decree holder and the court auction purchaser had committed fraud on the court and the claimants by suppressing material facts.",
        "Case Summary": "The court dismissed the appeals and revision petition, finding that the Insolvency Court had no jurisdiction to annul the sale deeds and that the annulment order was void and ineffective. The court also found that the decree holder and the court auction purchaser had committed fraud by suppressing material facts related to the existence of buildings on the property. The court directed the decree holder to deposit the withdrawn amount and allowed the court auction purchaser to withdraw the amount upon such deposit.",
        "": ""
    },
    {
        "Case No.": "SA.No.1240 of 2005",
        "Case Name": "Balasubramaniam vs Kannan",
        "Date": "03-06-2015",
        "Court": "HIGH COURT OF JUDICATURE AT MADRAS",
        "Case Status": "Disposed off",
        "Judges Involved": "K.B.K.VASUKI",
        "Sections and Clauses": "Section 100 of the Code of Civil Procedure, Section 28(1), 28(2), 28(3), 28(6), 28(7), Section 51(3), Section 55 of the Provincial Insolvency Act, Benami Transaction (prohibition) Act",
        "Facts": "Nandagopal Chettiar, heavily indebted, sold part of his property to Kamalammal. A creditor, Ramakrishnan, filed an insolvency petition against Nandagopal. The court adjudicated Nandagopal insolvent. The property vested with the Official Receiver. Ramanathan sued Nandagopal for debt recovery and obtained a decree. He then had the property sold at a court auction to Pethannan. The plaintiffs claim they had an agreement with Pethannan to purchase the property. The Official Receiver later sold the property to Chandravanitha.",
        "Petition Filed": "Plaintiffs sued for declaration of title and injunction against defendants, claiming they had a right to the property through their agreement with Pethannan.",
        "Legal Issues": "Whether the plaintiffs' claim to the property is valid given the prior insolvency proceedings and the sale of the property to the second defendant by the Official Receiver.",
        "Key Legal Questions": "Does the doctrine of relation back apply to this case, thus invalidating the sale of the property to Pethannan and subsequent transactions?",
        "Plaintiff's Arguments": "Plaintiffs argued that the court auction sale gave them a vested right to the property, they were bonafide purchasers for value, and the Official Receiver could only attach the sale consideration paid by them.",
        "Defendant's Arguments": "Defendant argued that the insolvency proceedings invalidated any transactions after the presentation of the petition, including the sale to Pethannan, and the plaintiffs were not bona fide purchasers without notice.",
        "Court's Reasoning": "The court found that the insolvency proceedings had priority, invalidating any transactions made during their pendency, including the sale to Pethannan. The plaintiffs were not bonafide purchasers without notice and thus did not have a valid claim to the property.",
        "Decision": "The second appeal was dismissed.",
        "Conclusion": "The plaintiffs' claim to the property was invalidated due to the prior insolvency proceedings and the sale of the property by the Official Receiver.",
        "Case Summary": "The plaintiffs sued for declaration of title and injunction based on their agreement with Pethannan, arguing they were bonafide purchasers. The defendants argued that the prior insolvency proceedings invalidated the sale to Pethannan. The court found for the defendants, determining that the insolvency proceedings were paramount and that the sale to Pethannan was invalid. This resulted in the dismissal of the second appeal.",
        "": ""
    },
    {
        "Case No.": "C.R.P.(PD).No.678 of 2016",
        "Case Name": "M.Sudhakar vs The Official Receiver",
        "Date": "16-11-2021",
        "Court": "High Court of Judicature at Madras",
        "Case Status": "Disposed off",
        "Judges Involved": "V.M.Velumani",
        "Sections and Clauses": "Article 227 of Constitution of India, Order VII Rule 11, Section 151 of Civil Procedure Code, Section 47 of the Provincial Insolvency Act, Section 18 of the Recovery of Debts Due to Banks & Financial Institutions Act, 1993",
        "Facts": "The petitioner purchased property in an auction sale brought by the 2nd respondent (a secured creditor) after insolvency proceedings were initiated against the property owner. The Official Receiver (1st respondent) was appointed as receiver in the insolvency proceedings. The Official Receiver sued the petitioner and 2nd respondent seeking declaration of his rights over the property and restraining them from claiming any interest in the property. The petitioner filed an application to reject the plaint arguing that he was an innocent purchaser and the sale was valid.",
        "Petition Filed": "The petitioner filed a Civil Revision Petition against the order dismissing his application to reject the plaint.",
        "Legal Issues": "Whether the sale of the property to the petitioner was valid despite the pending insolvency proceedings and whether the Official Receiver's suit is barred under Section 18 of the Recovery of Debts Due to Banks & Financial Institutions Act, 1993.",
        "Key Legal Questions": "Whether the Civil Court has jurisdiction to determine the validity of the sale of the property to the petitioner in light of the ongoing insolvency proceedings and the Official Receiver's claim over the property.",
        "Plaintiff's Arguments": "The petitioner argued that he was an innocent purchaser and the sale was valid. He also argued that the 2nd respondent, as a secured creditor, had the right to sell the property and the sale was binding on the Official Receiver.",
        "Defendant's Arguments": "The Official Receiver argued that the sale was invalid because it was conducted without informing him and that his rights over the property were vested under the insolvency proceedings.",
        "Court's Reasoning": "The court held that the question of whether the sale was valid and whether the Official Receiver's suit is barred under Section 18 of the Act is a mixed question of law and fact. The court also held that the averments in the written statement, the documents relied on by the defendants, and the averments in the affidavit filed in support of the application cannot be considered while deciding an application under Order VII Rule 11 of Civil Procedure Code.",
        "Decision": "The court dismissed the Civil Revision Petition and affirmed the lower court's order dismissing the petitioner's application to reject the plaint.",
        "Conclusion": "The court found no merit in the petitioner's arguments and upheld the Official Receiver's right to pursue his claim in the suit.",
        "Case Summary": "The petitioner challenged the Official Receiver's suit claiming he was an innocent purchaser and the sale was valid. The Official Receiver argued the sale was invalid and his rights over the property were vested under the insolvency proceedings. The court found the matter to be a mixed question of law and fact and upheld the lower court's decision to allow the suit to proceed.",
        "": ""
    },
    {
        "Case No.": "W.P.(MD).Nos.19871 to 19874 of 2018",
        "Case Name": "Mr.B.Pattabhiraman vs The Authorised Officer",
        "Date": "28-02-2019",
        "Court": "Madras High Court, Madurai Bench",
        "Case Status": "Disposed off",
        "Judges Involved": "R.Subbiah, B.Pugalendhi",
        "Sections and Clauses": "Article 226 of the Constitution of India, Securitisation and Reconstruction of Financial Assets and Enforcement of Security Interest Act, 2002 (SARFAESI Act), Section 13(2), Section 13(3A), Section 13(4), Section 17(1), Section 52(1)(a), Section 52(1)(b), Section 52(4), Section 52(5), Section 52(6), Section 53(1)(b)(ii), Section 53(1)(e)(i), Section 63, Section 64(2), Section 231, Section 238, Section 2(e), Section 14(3)(b), Section 126, Section 128, Section 141, Section 30, Section 31(1), Section 133, Section 14, Section 101, Section 96, Section 179, Section 249",
        "Facts": "The petitioner, a guarantor to a loan facility provided by the respondent-Bank to M/s.GB Engineering Enterprises Private Limited, filed a Writ Petition to quash an E-Auction Sale Notice issued by the respondent-Bank under the SARFAESI Act. The borrower company had defaulted on the loan, and the bank had initiated recovery proceedings. The borrower company had also filed for insolvency under the IBC, and the NCLT had ordered liquidation. The bank had relinquished its security interest in the borrower's property to the liquidator but proceeded to auction the guarantor's property under the SARFAESI Act.",
        "Petition Filed": "The petitioner filed a Writ Petition to quash the E-Auction Sale Notice, arguing that the respondent-Bank was not entitled to proceed against the guarantor's property under the SARFAESI Act when the borrower company was under liquidation proceedings under the IBC.",
        "Legal Issues": "The legal issues presented were whether the respondent-Bank was entitled to proceed against the guarantor's property under the SARFAESI Act while the borrower company was under liquidation proceedings under the IBC and whether the guarantor's liability was discharged due to the relinquishment of the security interest by the secured creditor.",
        "Key Legal Questions": "The key legal question addressed by the court was whether the secured creditor can proceed against the guarantor's property under the SARFAESI Act when the borrower company is under liquidation proceedings under the IBC.",
        "Plaintiff's Arguments": "The plaintiff's arguments were that the respondent-Bank was not entitled to proceed against the guarantor's property under the SARFAESI Act while the borrower company was under liquidation proceedings under the IBC and that the guarantor's liability was discharged due to the relinquishment of the security interest by the secured creditor.",
        "Defendant's Arguments": "The defendant's arguments were that the liability of the guarantor and principal debtor is co-extensive, not in alternative, and the Bank could proceed against the guarantor's property even if the borrower was in liquidation, as the guarantor's liability is not discharged by the relinquishment of the security interest.",
        "Court's Reasoning": "The court reasoned that the liability of the guarantor and the principal debtor is co-extensive, and there is no bar in proceeding against the guarantor's property under the SARFAESI Act, even when the borrower company is under liquidation proceedings under the IBC. The court concluded that the secured creditor is entitled to proceed under the SARFAESI Act against the guarantor's property, even when the borrower company is in the liquidation process under the IBC.",
        "Decision": "The court dismissed the Writ Petitions and held that the respondent-Bank was entitled to proceed under the SARFAESI Act against the guarantor's property, even when the borrower company was under liquidation proceedings under the IBC.",
        "Conclusion": "The court concluded that the respondent-Bank was entitled to proceed under the SARFAESI Act against the guarantor's property, even when the borrower company was in the liquidation process under the IBC, because the liability of the guarantor is co-extensive with that of the principal debtor.",
        "Case Summary": "The petitioners argued that the respondent-Bank was not entitled to proceed against the guarantor's property under the SARFAESI Act while the borrower company was under liquidation proceedings under the IBC. The respondent-Bank argued that the liability of the guarantor and the principal debtor is co-extensive, and they could proceed against the guarantor's property even if the borrower was in liquidation. The court agreed with the respondent-Bank and dismissed the petitions, concluding that the secured creditor is entitled to proceed under the SARFAESI Act against the guarantor's property, even when the borrower company is in the liquidation process under the IBC.",
        "": ""
    },
    {
        "Case No.": "C.R.P.(MD)No.236 of 2021",
        "Case Name": "M.Selvaraj vs Vetrikumar",
        "Date": "28-04-2023",
        "Court": "Madras High Court, Madurai Bench",
        "Case Status": "Order",
        "Judges Involved": "C.Saravanan",
        "Sections and Clauses": "Article 227 of the Constitution of India, Order XXI Rule 35(3) of C.P.C, Order XXI Rule 26 of C.P.C, Section 47 of C.P.C, Section 146 of C.P.C, Section 28(7) of the Provincial Insolvency Act, 1920",
        "Facts": "Two brothers, the second respondent and his two brothers, were declared insolvent in 2006, following a petition filed in 1999. The first respondent, the plaintiff in the case, had filed a suit against the brothers in 1999 and obtained an ex-parte decree in 2001. The first respondent purchased a portion of the brothers' property in 2003. The petitioners purchased the entire property from the Official Receiver in 2007. The first respondent filed a suit against the petitioners in 2007, arguing that his 2003 purchase was valid. The court ruled in favor of the petitioners, upholding the validity of the 2007 sale. The first respondent then attempted to take delivery of the property in 2019, which prompted the petitioners to file the current revision petition.",
        "Petition Filed": "The petitioners filed a Civil Revision Petition against an order allowing the first respondent to break open the door for taking delivery of the property.",
        "Legal Issues": "The petitioners argued that the first respondent’s 2003 purchase was invalid due to the insolvency proceedings and that the 2007 purchase by the petitioners was valid. They argued that the first respondent was attempting to take possession of the property illegally.",
        "Key Legal Questions": "Was the first respondent's attempt to take delivery of the property valid in light of the 2007 purchase by the petitioners?",
        "Plaintiff's Arguments": "The petitioners argued that the 2007 purchase was valid due to the insolvency proceedings and the subsequent sale by the Official Receiver. They argued that the first respondent had no right to the property.",
        "Defendant's Arguments": "The first respondent argued that his 2003 purchase was valid and that the petitioners were attempting to interfere with his right to possession.",
        "Court's Reasoning": "The court ruled that the first respondent’s attempt to take delivery of the property was not valid, citing Section 28(7) of the Provincial Insolvency Act, 1920. The court concluded that the 2007 purchase by the petitioners was valid and the first respondent's 2003 purchase was not.",
        "Decision": "The court set aside the order allowing the first respondent to break open the door for taking delivery of the property. The court remanded the case back to the lower court to pass fresh orders after disposal of the pending applications.",
        "Conclusion": "The court concluded that the first respondent's 2003 purchase was invalid due to the insolvency proceedings and that the petitioners' 2007 purchase was valid. The court found that the first respondent had no right to the property and that the lower court’s order allowing him to take delivery was invalid.",
        "Case Summary": "The petitioners challenged an order allowing the first respondent to take delivery of the property, arguing that the first respondent's 2003 purchase was invalid due to insolvency proceedings. The court ruled in favor of the petitioners, finding that the 2007 purchase by the petitioners was valid and the first respondent's 2003 purchase was not. The court set aside the order allowing the first respondent to take delivery of the property and remanded the case back to the lower court for further proceedings.",
        "": ""
    },
    {
        "Case No.": "602 of 2005",
        "Case Name": "S.M.Bakthavatchalu (deceased) vs M/S. Bhuvaneswari Theatre",
        "Date": "04-07-2016",
        "Court": "HIGH COURT OF JUDICATURE AT MADRAS",
        "Case Status": "Judgement",
        "Judges Involved": "V. Ramasubramanian",
        "Sections and Clauses": "Order IV, Rule 1 of Original Side Rules, Order VII, Rule 1, CPC",
        "Facts": "The case involved a dispute over a property sale agreement. The plaintiffs sued for specific performance of the agreement or, alternatively, for recovery of money. The defendants were the legal heirs of the deceased owner. A partial settlement was reached with some of the heirs, but the suit continued against the sixth defendant, who was also involved in insolvency proceedings.",
        "Petition Filed": "The plaintiffs filed a suit for specific performance of an agreement of sale or, in the alternative, for recovery of money.",
        "Legal Issues": "The legal issues revolved around the enforceability of the agreement of sale, the rights of the plaintiffs in the property, and the distribution of funds held by the Official Assignee in the insolvency proceedings.",
        "Key Legal Questions": "The key legal question was how to resolve the dispute between the plaintiffs and the sixth defendant, given the partial settlement with the other heirs and the funds held by the Official Assignee.",
        "Plaintiff's Arguments": "The plaintiffs argued that they were entitled to specific performance of the agreement of sale or, in the alternative, to recover the money owed to them.",
        "Defendant's Arguments": "The sixth defendant, in his capacity as the applicant in the insolvency proceedings, argued for a modification of the earlier order to enable him to take the amount lying with the Official Assignee.",
        "Court's Reasoning": "The court, in an attempt to resolve the deadlock, suggested that the amount held by the Official Assignee be shared between the plaintiffs and the sixth defendant. The court found that this suggestion was agreed upon and that the plaintiffs had entered into a memo of compromise with the sixth defendant.",
        "Decision": "The court decreed that the prayer for specific performance was rejected. It ordered that the plaintiffs receive the fixed deposit amount with accrued interest lying to the credit of the deceased mother of the sixth defendant. The sixth defendant was to take the amount lying in deposit in his own name. The Official Assignee was instructed to make payment accordingly.",
        "Conclusion": "The court's decision resolved the dispute between the plaintiffs and the sixth defendant, allowing for the distribution of the funds held by the Official Assignee and the dismissal of the claim for specific performance.",
        "Case Summary": "The plaintiffs filed a suit for specific performance of a sale agreement or for recovery of money. The defendants were the legal heirs of the deceased owner. After a partial settlement with some heirs, a compromise was reached between the plaintiffs and the sixth defendant. The court ordered the distribution of funds held by the Official Assignee and dismissed the claim for specific performance.",
        "": ""
    },
    {
        "Case No.": "CRP(PD)(MD)No.2233 of 2015 & MP(MD)No.1 of 2015",
        "Case Name": ")M.K.Seetharaman vs )M.K.Jeganathan",
        "Date": "04-10-2017",
        "Court": "Madras High Court, Madurai Bench",
        "Case Status": "Disposed off",
        "Judges Involved": "G.Jayachandran",
        "Sections and Clauses": "Order 7 Rule 11 CPC, Section 151 CPC, Section 29 of the Provincial Insolvency Act, Section 28(2) of the Provincial Insolvency Act",
        "Facts": "The plaintiffs, sons and daughter of Kulanthaivel Konar, filed a suit for partition and permanent injunction against the defendants. The defendants argued that the plaintiffs were declared insolvent in I.P.No.7/81 and the suit was not maintainable without leave of the court.",
        "Petition Filed": "The petitioners filed a revision petition challenging the lower court's dismissal of their application to reject the plaint under Order 7 Rule 11 CPC and Section 29 of the Provincial Insolvency Act.",
        "Legal Issues": "Whether the plaint could be rejected under Order 7 Rule 11 CPC and whether all further proceedings should be stayed or allowed to continue on such terms as the court may impose under Section 29 of the Provincial Insolvency Act.",
        "Key Legal Questions": "Whether the plaintiffs' suit for partition was maintainable despite the insolvency proceedings against them.",
        "Plaintiff's Arguments": "The plaintiffs argued that the suit was maintainable and that the insolvency proceedings were not pending. They also argued that they were not creditors of the defendants and therefore did not require leave of the court.",
        "Defendant's Arguments": "The defendants argued that the plaint should be rejected under Order 7 Rule 11 CPC and that further proceedings should be stayed under Section 29 of the Provincial Insolvency Act because the plaintiffs were declared insolvent and had not been discharged from insolvency.",
        "Court's Reasoning": "The court held that the plaint could not be rejected under Order 7 Rule 11 CPC as the suit had already commenced and the plaintiffs had a valid cause of action. The court also held that Section 29 of the Provincial Insolvency Act did not apply because the insolvency proceedings were not pending and the plaintiffs were not creditors of the defendants.",
        "Decision": "The court dismissed the revision petition and upheld the lower court's order rejecting the defendants' application.",
        "Conclusion": "The court found that the plaintiffs' suit for partition was maintainable despite the insolvency proceedings against them. The court held that the insolvency proceedings did not bar the suit because they were not pending and the plaintiffs were not creditors of the defendants.",
        "Case Summary": "The defendants argued that the plaintiffs' suit was not maintainable because they had been declared insolvent and had not been discharged from insolvency. The court rejected this argument, holding that the insolvency proceedings did not bar the suit because they were not pending and the plaintiffs were not creditors of the defendants. The court dismissed the revision petition, upholding the lower court's decision.",
        "": ""
    },
    {
        "Case No.": "O.S.A.Nos.26 to 28 and 183 of 2017",
        "Case Name": "K.Dhanalakshmi Ammal vs T.Radha",
        "Date": "10-06-2017",
        "Court": "HIGH COURT OF JUDICATURE AT MADRAS",
        "Case Status": "Judgement",
        "Judges Involved": "RAJIV SHAKDHER, N.SATHISH KUMAR",
        "Sections and Clauses": "Order XXXVI, Rule 1 of the Original Side Rule, Section 41 of the Presidency Towns Insolvency Act, 1909, Section 21 of the 1909 Act, Section 23 of the 1909 Act, Section 24 of the 1909 Act, Section 27 of the 1909 Act, Order XVII, Rule 10(1) of the Insolvency Rules, 1958",
        "Facts": "Ms.T.Radha was adjudicated insolvent based on her own petition. She had disclosed debts to a secured creditor and unsecured creditors. She owned a property but failed to file details of creditors, debtors, or assets as required. The OA annulled the order of adjudication after Ms.T.Radha failed to file an application for discharge. She settled all debts without the OA's knowledge. Messrs K.Dhanalakshmiammal and A.V.K.Balamurugan claimed to be bona fide purchasers of a part of the property and that Ms.T.Radha had shown fictitious creditors.",
        "Petition Filed": "Ms.T.Radha sought to set aside the order annulling her adjudication. Messrs K.Dhanalakshmiammal and A.V.K.Balamurugan sought annulment of the order of adjudication.",
        "Legal Issues": "Whether Ms.T.Radha, having paid the dues of all creditors, was entitled to seek the setting aside of the order annulling her adjudication. Whether the OA was entitled to commission. What relief should be granted to Messrs K.Dhanalakshmiammal and A.V.K.Balamurugan.",
        "Key Legal Questions": "Whether the insolvency proceedings should continue after all creditors have been paid.",
        "Plaintiff's Arguments": "Ms.T.Radha argued that she paid all creditors and that the insolvency proceedings should be terminated.",
        "Defendant's Arguments": "The OA argued that commission should be paid as all creditors were paid. Messrs K.Dhanalakshmiammal and A.V.K.Balamurugan claimed to be bona fide purchasers and that Ms.T.Radha showed fictitious creditors.",
        "Court's Reasoning": "The Court found that no purpose was served in continuing the insolvency proceedings because all creditors had been paid and no fresh claims were lodged. The Court concluded that the commission provision was not applicable because Ms.T.Radha settled the debts without the OA's involvement. The Court ruled that the appeals filed by Messrs K.Dhanalakshmiammal and A.V.K.Balamurugan were infructuous.",
        "Decision": "The Court allowed O.S.A.No. 183 of 2017, set aside the order annulling the adjudication, and set aside the order of adjudication. The Court dismissed O.S.A.Nos.26 to 28 of 2017 as infructuous.",
        "Conclusion": "The Court ruled that Ms.T.Radha was entitled to have the adjudication order set aside as all creditors had been paid and there were no further claims. The Court ruled that the OA was not entitled to commission. The Court dismissed the appeals of Messrs K.Dhanalakshmiammal and A.V.K.Balamurugan as infructuous.",
        "Case Summary": "Ms.T.Radha sought to set aside the order annulling her adjudication. The OA argued that commission should be paid. Messrs K.Dhanalakshmiammal and A.V.K.Balamurugan claimed to be bona fide purchasers and that Ms.T.Radha showed fictitious creditors. The Court ruled that the OA was not entitled to commission and the appeals of Messrs K.Dhanalakshmiammal and A.V.K.Balamurugan were infructuous. The Court set aside the order annulling the adjudication and the adjudication order.",
        "": ""
    },
    {
        "Case No.": "S. A.No.654 of 2011",
        "Case Name": "Shanmugam vs Palanisamy",
        "Date": "21-12-2016",
        "Court": "THE HIGH COURT OF JUDICATURE AT MADRAS",
        "Case Status": "Disposed off",
        "Judges Involved": "T.Ravindran",
        "Sections and Clauses": "Section 100 of Civil Procedure Code, Section 20 of the Negotiable Instruments Act",
        "Facts": "The plaintiff sued the defendant for recovery of money based on a promissory note. The defendant claimed he did not execute the promissory note and was insolvent at the time.",
        "Petition Filed": "The plaintiff filed a suit for recovery of money based on a promissory note.",
        "Legal Issues": "Whether the promissory note was genuine and whether the plaintiff was entitled to recover the money.",
        "Key Legal Questions": "Whether the defendant's claim of insolvency and non-execution of the promissory note was credible.",
        "Plaintiff's Arguments": "The plaintiff argued that the defendant had borrowed money and executed the promissory note, and the defendant did not respond to the legal notice.",
        "Defendant's Arguments": "The defendant argued that he did not execute the promissory note, was insolvent, and his signature was misused.",
        "Court's Reasoning": "The court found the promissory note genuine, the defendant's insolvency claim unreliable, and the defendant's contradictory defense weak.",
        "Decision": "The court dismissed the second appeal and affirmed the lower court's judgment in favor of the plaintiff.",
        "Conclusion": "The court found no substantial question of law and dismissed the appeal.",
        "Case Summary": "The plaintiff successfully sued the defendant for money based on a promissory note. The defendant's claims of insolvency and non-execution were rejected due to a lack of credible evidence and contradictory defenses. The court upheld the lower court's decision in favor of the plaintiff.",
        "": ""
    },
    {
        "Case No.": "Crl.O.P No.28447 of 2009",
        "Case Name": "Rajeswaran Samuel vs M/S.Barclays Bank Plc",
        "Date": "15-03-2017",
        "Court": "IN THE HIGH COURT OF JUDICATURE AT MADRAS",
        "Case Status": "Order",
        "Judges Involved": "M.V.Muralidaran",
        "Sections and Clauses": "Section 482 of Criminal Procedure Code, Section 138 to 142 of Negotiable Instruments Act, Section 17 of The Presidency Towns Insolvency Act, 1909, Section 69 of the Insolvency Act, Section 103 of the Insolvency Act, Section 15 and Section 24 of the Insolvency Act",
        "Facts": "Rajeswaran Samuel, the petitioner, was declared insolvent by the court. Barclays Bank PLC, the respondent, filed a complaint under Section 138 of the Negotiable Instruments Act against the petitioner for dishonoring a check issued by the petitioner to the respondent. The petitioner argued that the respondent had knowledge of the insolvency proceedings and that the complaint was an abuse of the legal process.",
        "Petition Filed": "The petitioner filed a criminal original petition under Section 482 of the Criminal Procedure Code to quash the complaint.",
        "Legal Issues": "Whether the respondent could file a complaint under the Negotiable Instruments Act while the insolvency proceedings were pending and the petitioner's property was under the custody of the Official Assignee.",
        "Key Legal Questions": "Whether the respondent's complaint was an abuse of the legal process.",
        "Plaintiff's Arguments": "The petitioner argued that he was insolvent and that the respondent had knowledge of the insolvency proceedings. The petitioner argued that the respondent should have filed an application before the Official Assignee instead of filing a complaint. The petitioner argued that the respondent's complaint was an abuse of the legal process.",
        "Defendant's Arguments": "There was no representation on behalf of the respondent.",
        "Court's Reasoning": "The court found that the respondent had knowledge of the insolvency proceedings. The court found that the respondent should have filed an application before the Official Assignee instead of filing a complaint. The court found that the respondent's complaint was an abuse of the legal process.",
        "Decision": "The court quashed the complaint as not maintainable and an abuse of the legal process.",
        "Conclusion": "The court concluded that the respondent had to pursue his claim through the insolvency proceedings and that the complaint was an abuse of the legal process.",
        "Case Summary": "The petitioner, Rajeswaran Samuel, was declared insolvent by the Madras High Court. The respondent, Barclays Bank PLC, filed a complaint against the petitioner under the Negotiable Instruments Act for dishonoring a check. The petitioner argued that the complaint was an abuse of the legal process because the respondent had knowledge of the insolvency proceedings. The court found in favor of the petitioner, quashing the complaint as not maintainable. The court held that the respondent should have filed an application before the Official Assignee instead of filing a complaint.",
        "": ""
    },
    {
        "Case No.": "O.S.A.Nos.214 to 219 of 2016",
        "Case Name": "The Official Assignee vs S.Arjunlal Sunderdas",
        "Date": "26-10-2016",
        "Court": "High Court of Judicature at Madras",
        "Case Status": "Disposed off",
        "Judges Involved": "Sanjay Kishan Kaul, R.Mahadevan",
        "Sections and Clauses": "Sections 55 and 57 of the Presidency Towns Insolvency Act III of 1909",
        "Facts": "The Official Assignee sought to challenge the sale of a property by Amarnath Reddy to Arjunlal Sunderdas, the insolvent, claiming the transaction was not bona fide and the property was undervalued.",
        "Petition Filed": "The Official Assignee sought to avoid the transfer of the property under Sections 55 and 57 of the Presidency Towns Insolvency Act.",
        "Legal Issues": "Whether the sale of the property was in good faith and for valuable consideration, thus exempt from being voided under the Insolvency Act.",
        "Key Legal Questions": "Whether the transaction was a bona fide purchase for valuable consideration or a transfer made to defraud creditors.",
        "Plaintiff's Arguments": "The Official Assignee argued that the sale was not bona fide due to the undervaluation of the property and that Amarnath Reddy was aware of Arjunlal Sunderdas' insolvent circumstances.",
        "Defendant's Arguments": "Amarnath Reddy argued that the sale was in good faith for valuable consideration and that he was not aware of Arjunlal Sunderdas' financial difficulties.",
        "Court's Reasoning": "The court found that the sale price was significantly higher than the guideline value and that Amarnath Reddy had no prior knowledge of Arjunlal Sunderdas' insolvency.",
        "Decision": "The court dismissed the appeals, finding that the sale was bona fide and for valuable consideration.",
        "Conclusion": "The court concluded that the Official Assignee had failed to prove that the sale of the property was not in good faith and for valuable consideration.",
        "Case Summary": "The Official Assignee challenged the sale of a property by Amarnath Reddy to Arjunlal Sunderdas, arguing that the transaction was not bona fide and the property was undervalued. Amarnath Reddy claimed the sale was in good faith for valuable consideration. The court, after examining the sale price and finding no evidence of Amarnath Reddy's knowledge of Arjunlal Sunderdas' insolvency, dismissed the appeals and upheld the sale as bona fide.",
        "": ""
    }
]

